### ISSUE TITLE
Non-issue: Do you mind if I call your fork "the right one"? (link to it, etc.)

### ISSUE THREAD

**Issue by geoff-nixon** [Kentzo/F-Script#6]
Hi — so I wanted to double check this was ok with you — are you ok with me linking to this fork as the "correct one"? I.e., where to get the most up-to-date code, and to submit issues/pull requests here? Because the mugginsoft fork doesn't seem open to merging your PRs (which are necessary), and I think it would be better to not splinter off a fourth time, if it can be avoided...?

**Comment by Kentzo** [comment]
The goal of this fork is to support new versions of OSX and therefore changes in builtin framework. In other words support of future versions is preferred over backward compatibility.

If it's okay with you, then feel free to call this fork official.

**Comment by geoff-nixon** [comment]
Yes, that's exactly what I mean. Somewhere for new and updated code. Great!
