### ISSUE TITLE
Problem loading framework into lldb

### ISSUE THREAD

**Issue by mts749** [Kentzo/F-Script#7]
Environment: OSX 10.9.2, Xcode 5.1 command line tools. lldb is attached to TextEdit

I am using the FScript framework from the 10.9 distribution at:
     https://github.com/Kentzo/F-Script/releases/tag/v2.2

When I attempt to load the 2.2 framework into lldb it fails. At first I thought it was that some files were marked with "com.apple.quarantine" so I eliminated all the extended attributes using xattr checked the permission. lldb still refuses to load the framework:

```
(lldb) attach 25300
Process 25300 stopped
Executable module set to "/Applications/TextEdit.app/Contents/MacOS/TextEdit".
Architecture set to: x86_64-apple-macosx.
(lldb) p (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScriptFramework.framework"] load]
(BOOL) $0 = NO
```

However, it works when I use the older framework from
    http://www.fscript.org/download/download.htm.
Here is the output from lldb:

```
(lldb) p (BOOL)[[NSBundle bundleWithPath:@"/Library/Frameworks/FScript.framework"] load]
(BOOL) $1 = YES
```

Any ideas on why the newer framework won't load?

**Comment by Kentzo** [comment]
Have you tried https://github.com/Kentzo/F-Script/releases/tag/v2.2.1 ?

**Comment by mts749** [comment]
I hadn't. Worked like a charm. Thanks for the pointer,
