### ISSUE TITLE
Quote substitution

### ISSUE THREAD

**Issue by hyperjeff** [Kentzo/F-Script#8]
In 10.9 I found that the F-Script shell would rewrite my ' and " as curly quotes, and no simple way I could figure out to turn them off. I downloaded the source and added the line

[self setAutomaticQuoteSubstitutionEnabled:NO];

to line 119 of ShellView.m and now it no longer has that problem. Was this just a problem for me? At any rate, simple fix if it affects others.

**Comment by Kentzo** [comment]
@hyperjeff Never occurred to me, probably it depends on your locale and language.

Did you have a problem with auto spelling corrections as well?

**Comment by hyperjeff** [comment]
At least on my machine, I don't see that spelling correction is turned on, which seems right. I can't think of a good reason for it to be on. But again, it seems to currently be off anyway. (Though not positive if that's due to some configuration specific to my machine or not.)

**Comment by Kentzo** [comment]
Free free to send a pull request with your fix.

**Comment by Kentzo** [comment]
@hyperjeff Should be resolved: https://github.com/Kentzo/F-Script/pull/9
